syntax = "proto3";

package myservice;

option go_package = "github.com/dinoagera/protos/gen/go/myservice;myservice";

message Task {
    int64 id = 1;
    string title = 2;
    string description = 3;
    bool done = 4;
}
message User {
    int64 uid = 1;
    string username = 2;
    string password = 3;
    bool active = 4;
}
message CreateRequest {
    string title = 1;
    string description = 2;
}
message CreateResponse {
    int64 id = 1;
    string message = 2;
}
message DeleteRequest {
    int64 id = 1;
}
message DeleteResponse {
    string message = 1;
}
message DoneRequest {
    int64 id = 1;
}
message DoneResponse {
    string message = 1;
}
message GetAllRequest {}
message GetAllResponse {
    repeated Task tasks = 1;
}
message ChangeRequest {
    int64 id = 1;
    string title = 2;
    string description = 3;
}
message ChangeResponse {
    string message = 1;
}
message RegisterRequest {
    string username = 1;
    string password = 2;
}
message RegisterResponse {
    string message = 1;
}
message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
    string message = 2;
}
service DBWork {
    rpc CreateTask (CreateRequest) returns (CreateResponse);
    rpc DeleteTask (DeleteRequest) returns (DeleteResponse);
    rpc DoneTask (DoneRequest) returns (DoneResponse);
    rpc GetAllTask (GetAllRequest) returns (GetAllResponse);
    rpc ChangeTask (ChangeRequest) returns (ChangeResponse);
}
service Auth {
    rpc RegisterUser (RegisterRequest) returns (RegisterResponse);
    rpc LoginUser (LoginRequest) returns (LoginResponse);
}